<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>PhotoRenameAIHash</RootNamespace>
    <AssemblyName>PhotoRenameAIHash</AssemblyName>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- 单项目 MSIX 打包：EnableMsixTooling + GenerateAppxPackageOnBuild=true 才会产出并签名 .msix -->
    <GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>
    <NoWarn>$(NoWarn);NU1701;CS1591</NoWarn>
    <EnableMsixTooling>true</EnableMsixTooling>
    <PublishProfile>Properties\PublishProfiles\win10-$(Platform).pubxml</PublishProfile>
    <AppxPackageSigningEnabled>true</AppxPackageSigningEnabled>
    <PackageCertificateKeyFile>PhotoRenameAIHash.pfx</PackageCertificateKeyFile>
    <PackageCertificateThumbprint>9F089DB28AE4CB075CBAC1D1D8073E382271CF3A</PackageCertificateThumbprint>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240428000" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.3233" />
    <PackageReference Include="Microsoft.VCRTForwarders.140" Version="1.1.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>

</Project>
